# Travis Build File for Percy
#

language: python

python:
  - "2.7"
  - "3.5"

before_install:
  - echo "Test"
  - echo "$(python -V)"

install:
  - pip install requests
  - pip install flask
  - pip install electrum

script:
  - true
