# Travis Build File for Percy
#

language: python

sudo: required

python:
  - "3.5"

addons:
  mariadb: 10.0

before_install:
  - echo "Test"
  - echo "$(python -V)"

install:
  - pip install requests
  - pip install flask
  - pip install flask_cors
  - pip install pymysql
  - ./travis/electrum_travis_setup.sh
  - ./travis/mariadb_travis_setup.sh
  - ./travis/percy_api_travis_setup.sh

script:
  - ./travis/do_ps_tests.py
