# Travis Build File for Percy
#

language: python

python:
  - "3.5"

before_install:
  - echo "Test"
  - echo "$(python -V)"

install:
  - pip install requests
  - pip install flask
  - ./travis/electrum_travis_setup.sh

script:
  - true
